* **Development**

  * :doc:`Bug </contributing/development/bug>`
  * :doc:`Patch </contributing/development/patch>`
  * :doc:`Security </contributing/development/security>`
  * :doc:`Tests </contributing/development/test>`
  * :doc:`Standards</contributing/development/standard>`
  * :doc:`License </contributing/development/license>`

* **Documentation**

  * :doc:`Overview </contributing/documentation/overview>`
  * :doc:`Contribute </contributing/documentation/contribute>`
  * :doc:`Standards </contributing/documentation/standard>`
  * :doc:`License </contributing/documentation/license>`
